"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Main.py']
DATA_FILES = ["Cli.py", "com_permissin.py", "connection_mode.py", "commands.py", "var.py"]
OPTIONS = {
    'argv_emulation': True,
    'includes': 'can.interfaces.slcan'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)